apps/course/urls.py
from django.urls import path, include

app_name = 'course'

urlpatterns = [
    path('v1/', include('apps.course.v1.urls'))
]

apps/course/v1/urls.py
from django.urls import path
# from .views import course_view, course_detail
from .views import CourseListView, CourseDetailView, lesson_detail

urlpatterns = [
    # path('', course_view, name='course_list'),
    # path('detail/<int:pk>/', course_detail, name='detail'),

    path('', CourseListView.as_view(), name = 'course_list'),
    path('detail/<int:pk>/', CourseDetailView.as_view(), name = 'detail'),
    path('detail/<int:course_id>/lesson/<int:pk>/', lesson_detail, name = 'course_lesson_detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),

    # local apps
    path('account/', include('apps.account.urls', namespace='account')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('', include('apps.main.urls', namespace='main')),
    path('', RedirectView.as_view(pattern_name='main:index')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/course/models.py
from apps.account.models import Profile
from apps.main.models import Category, Tag
from ckeditor.fields import RichTextField
from django.db import models


def image_uploader(instance, filename):
    return f'{instance.title}/{filename}'


class Timestamp(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Course(Timestamp):
    DIFFICULTY = (
        (0, 'Beginner'),
        (1, 'Intermediate'),
        (2, 'Advanced'),
    )
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField(Tag)
    image = models.ImageField(upload_to=image_uploader)
    title = models.CharField(max_length=225)
    body = RichTextField()
    price = models.DecimalField(decimal_places=2, max_digits=4, null=True, blank=True)
    discount_price = models.DecimalField(decimal_places=2, max_digits=4, null=True, blank=True)
    difficulty = models.IntegerField(choices=DIFFICULTY, default=0)
    is_free = models.BooleanField(default=False)

    def __str__(self):
        return self.title



def file_path(instance, filename):
    return f'{instance.lesson.course.title}/{instance.lesson.title}/{filename}'


class Lesson(Timestamp):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(max_length=225)
    body = RichTextField()

    def __str__(self):
        return self.title


class LessonFiles(Timestamp):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    file = models.FileField(upload_to=file_path)  # course_name/lesson_name/file
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return self.lesson.title


class SoldCourse(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.profile.user.username} -> {self.course.title}'

apps/course/v1/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView

from ..models import Course, Lesson, LessonFiles
from apps.main.models import Category, Tag
from apps.main.v1.forms import SubscribeForm


# def course_view(request):
#     courses = Course.objects.order_by('-id')
#     category_list = Category.objects.all()
#     tags = Tag.objects.all()
#     recent_courses = Course.objects.order_by('-id')[:3]
#
#     cat = request.GET.get('cat')
#     tag = request.GET.get('tag')
#     if cat:
#         courses = courses.filter(category__title__exact=cat)
#     if tag:
#         courses = courses.filter(tags__title__exact=tag)
#
#     form = SubscribeForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         return redirect('.')
#
#     ctx = {
#         'object_list': courses,
#         'category_list': category_list,
#         'tags': tags,
#         'recent_courses': recent_courses,
#         'form': form,
#     }
#     return render(request, 'course/courses.html', ctx)
#
#
# def course_detail(request, pk):
#     course = get_object_or_404(Course, id=pk)
#     ctx = {
#         'object': course,
#     }
#     return render(request, 'course/course-single.html', ctx)
#


class CourseListView(ListView):
    queryset = Course.objects.all()
    paginate_by = 1

    def get_context_data(self, *, object_list=None, **kwargs):
        ctx = super().get_context_data()
        ctx['categories'] = Category.objects.all()
        ctx['tags'] = Tag.objects.all()
        ctx['recent_courses'] = Course.objects.order_by('-id')[:3]
        return ctx

    def get_queryset(self):
        qs = super().get_queryset()
        tag = self.request.GET.get('tag')
        cat = self.request.GET.get('cat')
        q = self.request.GET.get('q')
        q_condition = Q()
        if q:
            q_condition = Q(title__icontains=q)
        q_category = Q()
        if cat:
            q_category = Q(category__title__exact=cat)
        q_tag = Q()
        if tag:
            q_tag = Q(tags__title__exact=tag)
        qs = qs.filter(q_condition, q_category, q_tag)
        return qs



class CourseDetailView(DetailView):
    queryset = Course.objects.all()
    template_name = 'course/course_detail.html'

    def get_context_data(self,*args, **kwargs):
        ctx = super().get_context_data()
        ctx['recent_courses'] = Course.objects.order_by('-id')[:3]
        ctx['categories'] = Category.objects.all()
        ctx['randomly_5_courses'] = Course.objects.order_by('?')[:5]
        ctx['tags'] = Tag.objects.all()
        return ctx

    def get_queryset(self):
        qs = super().get_queryset()
        tag = self.request.GET.get('tag')
        cat = self.request.GET.get('cat')
        q = self.request.GET.get('q')
        q_condition = Q()
        if q:
            q_condition = Q(title__icontains=q)
        q_category = Q()
        if cat:
            q_category = Q(category__title__exact=cat)
        q_tag = Q()
        if tag:
            q_tag = Q(tags__title__exact=tag)
        qs = qs.filter(q_condition, q_category, q_tag)
        return qs



def lesson_detail(request, course_id, pk):
    lesson = Lesson.objects.get(id=pk)
    main_video = LessonFiles.objects.filter(lesson_id=pk, is_main=True).first()
    # course = Course.objects.get(id=course_id)
    randomly_5_courses = Course.objects.order_by('?')[:5]

    ctx = {
        "lesson": lesson,
        "randomly_5_courses": randomly_5_courses,
        "main_video": main_video,
    }
    return render(request, 'course/course_lesson.html', ctx)

templates/course/course_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({{ object.image.url }});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-7 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">{{ object.title }}</h1>
                    <p class="bcrumb"><a href="{% url 'main:index' %}">Home</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <a href="{% url 'course:course_list' %}">Course</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <span class="current">{{ object.title }}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="site-section bg-light element-animate">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8 order-md-2 mb-5">
                <div class="row">
                    <div class="col-md-12">
                        <img src="{{ object.image.url }}" alt="" class="img-fluid">
                    </div>
                </div>
                <section class="episodes">
                    <div class="container">
                        <div class="row mb-5">
                            <div class="col-md-12 pt-5">
                                <h2>Description</h2>
                                    <p>
                                        {{ object.body|safe }}
                                    </p>
                            </div>
                        </div>
                    </div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 mb-2">
                                <h2>Lesson</h2>
                            </div>
                        </div>
                        {% for lesson in object.lesson_set.all %}
                        <div class="row {% if forloop.counter|divisibleby:2 %}bg-light{% endif %} align-items-center p-4 episode">
                            <div class="col-md-10">
                                <p class="meta">Episode {{ forloop.counter }}</p>
                                <h2><a href="{% url 'course:course_lesson_detail' object.id lesson.id %}">{{ lesson.title }}</a></h2>
                                <p>{{ lesson.body|slice:100|safe }}</p>
                            </div>
                            <div class="col-md-2 text-center">
                                <a href="#" class="play"><span class="ion-ios-play"></span></a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </section>
            </div>

            <div class="col-md-6 col-lg-4 order-md-1">
                <div class="block-29 mb-5">
                    <h2 class="heading">Course Details</h2>
                    <ul>
                        <li><span class="text-1">Lessons: </span> <span class="text-2">{{ object.lesson_set.count }}</span></li>
                        <li><span class="text-1">Difficulty: </span> <span class="text-2">{{ object.get_difficulty_display }}</span></li>
                        <li><span class="text-1">Language: </span> <span class="text-2">English</span></li>
                        <li><span class="text-1">Price: </span> <span class="text-2">
                                        {% if object.discount_price %}
                                            <del class="mr-3">${{ object.discount_price }}</del>
                                        {% endif %}
                                        {% if object.is_free %}
                                        <span>Free</span>
                                        {% else %}
                                        <span>${{ object.price }}</span>
                                        {% endif %}
                        </span></li>
                    </ul>
                </div>
                <div class="block-28 text-center mb-5">
                    <figure>
                        <img src="{{ object.author.image.url }}" alt="" class="img-fluid">
                    </figure>
                    <h2 class="heading">{{ object.author }}</h2>
                    <h3 class="subheading">{{ object.author.bio|safe }}</h3>
                    <p>
                        <a href="#" class="fa fa-twitter p-2"></a>
                        <a href="#" class="fa fa-facebook p-2"></a>
                        <a href="#" class="fa fa-linkedin p-2"></a>
                    </p>
                    <p>Hi I'm Mark Stewart, consectetur adipisicing elit. Quibusdam nulla beatae modi itaque nemo magni
                        molestiae explicabo sint dolorum cum! Nam iste eligendi autem voluptates illo veritatis veniam
                        laudantium enim!</p>
                </div>
                <div class="block-25 mb-5">
                    <div class="heading">Recent Courses</div>
                    <ul>

                        {% for course in recent_courses %}

                        <li>
                            <a href="{% url 'course:detail' course.id %}" class="d-flex">
                                <figure class="image mr-3">
                                    <img src="{{ course.image.url }}" alt="" class="img-fluid">
                                </figure>
                                <div class="text">
                                    <h3 class="heading">{{ course.title }}</h3>
                                    {% if course.discount_price %}
                                            <del class="mr-3">${{ course.discount_price }}</del>
                                        {% endif %}
                                        {% if course.is_free %}
                                        <span>Free</span>
                                        {% else %}
                                        <span>${{ course.price }}</span>
                                        {% endif %}
                                </div>
                            </a>
                        </li>

                        {% endfor %}

                    </ul>
                </div>
               <div class="block-24 mb-5">
                    <h3 class="heading">Categories</h3>
                    <ul>
                        {% for category in categories %}
                        <li><a href="{% if request.GET %}{{ request.get_full_path }}&cat={{ category }}{% else %}{% url 'course:course_list' %}?cat={{ category }}{% endif %}">{{ category }}<span>{{ category.course_set.count }}</span></a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-26">
                    <h3 class="heading">Tags</h3>
                    <ul>
                        {% for tag in tags %}
                        <li><a href="{% if request.GET %}{{ request.get_full_path }}&tag={{ tag }}{% else %}{% url 'course:course_list' %}?tag={{ tag }}{% endif %}">{{ tag }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row justify-content-center mb-5 element-animate">
            <div class="col-md-7 text-left section-heading">
                <h2 class="text-primary heading">You May Also Like</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore
                    sapiente.</p>
            </div>
        </div>
    </div>
    <div class="container-fluid block-11 element-animate">
        <div class="nonloop-block-11 owl-carousel">
            {% for course in randomly_5_courses %}

            <div class="item">
                <div class="block-19">
                    <figure>
                        <img src="{{ course.image.url }}" alt="Image" class="img-fluid">
                    </figure>
                    <div class="text">
                        <h2 class="heading"><a href="#">{{ course.title }}</a></h2>
                        <p class="mb-4">{{ course.body|safe }}</p>
                        <div class="meta d-flex align-items-center">
                            <div class="number">
                                <span>{{ course.soldcourse_set.count }}</span>
                            </div>
                            <div class="price text-right">
                                {% if course.discount_price %}
                                    <del class="mr-3">${{ course.discount_price }}</del>
                                {% endif %}
                                {% if course.is_free %}
                                    <span>Free</span>
                                {% else %}
                                    <span>${{ course.price }}</span>
                                {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</div>

<div class="py-5 block-22">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-4 mb-md-0 pr-md-5">
                <h2 class="heading">Create cool websites</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
            </div>
            <div class="col-md-6">
                <form action="#" class="subscribe">
                    <div class="form-group">
                        <input type="email" class="form-control email" placeholder="Enter email">
                        <input type="submit" class="btn btn-primary submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/course/course_lesson.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({{ lesson.course.image.url }});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-7 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">{{ lesson.title }}</h1>
                    <p class="bcrumb"><a href="{% url 'main:index' %}">Home</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <a href="{% url 'course:course_list' %}">Course</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <span class="current">{{ lesson.course.title }}</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="site-section bg-light element-animate">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-12 order-md-2 mb-5">
                <div class="row">
                    <div class="col-md-12">
                        <video style="width: 100%" autoplay controls src="{{ main_video.file.url }}"></video>
                    </div>
                </div>
                <section class="episodes">
                    <div class="container">
                        <div class="row mb-5">
                            <div class="col-md-12 pt-5">
                                <h2>Description</h2>
                                    <p>
                                        {{ lesson.body|safe }}
                                    </p>
                            </div>
                        </div>
                    </div>
                </section>
            </div>


        </div>
    </div>
</div>
<div class="site-section bg-light">
    <div class="container">
        <div class="row justify-content-center mb-5 element-animate">
            <div class="col-md-7 text-left section-heading">
                <h2 class="text-primary heading">You May Also Like</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore
                    sapiente.</p>
            </div>
        </div>
    </div>
    <div class="container-fluid block-11 element-animate">
        <div class="nonloop-block-11 owl-carousel">
            {% for course in randomly_5_courses %}

            <div class="item">
                <div class="block-19">
                    <figure>
                        <img src="{{ course.image.url }}" alt="Image" class="img-fluid">
                    </figure>
                    <div class="text">
                        <h2 class="heading"><a href="#">{{ course.title }}</a></h2>
                        <p class="mb-4">{{ course.body|safe }}</p>
                        <div class="meta d-flex align-items-center">
                            <div class="number">
                                <span>{{ course.soldcourse_set.count }}</span>
                            </div>
                            <div class="price text-right">
                                {% if course.discount_price %}
                                    <del class="mr-3">${{ course.discount_price }}</del>
                                {% endif %}
                                {% if course.is_free %}
                                    <span>Free</span>
                                {% else %}
                                    <span>${{ course.price }}</span>
                                {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/course/course_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({% static 'images/big_image_2.jpg' %});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-7 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">Courses</h1>
                    <p class="bcrumb"><a href="{% url 'main:index' %}">Home</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <span class="current">Courses</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="site-section bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-8 order-md-2">
                <div class="row">
                    {% for object in object_list %}
                    <div class="col-md-12 col-lg-6 mb-5">
                        <div class="block-19">
                            <figure>
                                <a href="{% url 'course:detail' object.id %}"><img src="{{ object.image.url }}" alt="Image" class="img-fluid"></a>
                            </figure>
                            <div class="text">
                                <h2 class="heading"><a href="{% url 'course:detail' object.id %}">{{ object.title }}</a></h2>
                                <p class="mb-4">{{ object.body|safe|slice:100 }}</p>
                                <div class="meta d-flex align-items-center">
                                    <div class="number">
                                        <span>{{ object.soldcourse_set.count }}</span>
                                    </div>
                                    <div class="price text-right">
                                        {% if object.discount_price %}
                                            <del class="mr-3">${{ object.discount_price }}</del>
                                        {% endif %}
                                        {% if object.is_free %}
                                        <span>Free</span>
                                        {% else %}
                                        <span>${{ object.price }}</span>
                                        {% endif %}
                                    </div>
                            </div>
                        </div>
                    </div>
                    </div>
                                    {% endfor %}
                    </div>
                <div class="row mb-5">
                    <div class="col-md-12 text-center">
                        <div class="block-27">
                                {% if is_paginated %}
                                    <ul>
                                        {% if page_obj.has_previous %}
                                            <li><a href="?page={{ page_obj.previous_page_number }}">&lt;</a></li>
                                        {% endif %}
                                        {% for page in paginator.page_range %}
                                            {% if page_obj.number == page %}
                                                <li class="active"><span>{{ page }}</span></li>
                                            {% else %}
                                                <li><a href="?page={{ page }}">{{ page }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if page_obj.has_next %}
                                            <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>
                                        {% endif %}
                                    </ul>
                                {% endif %}
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 col-lg-4 order-md-1">
                <div class="block-24 mb-5">
                    <h3 class="heading">Categories</h3>
                    <ul>
                        {% for category in categories %}
                        <li><a href="{% if request.GET %}{{ request.get_full_path }}&cat={{ category }}{% else %}?cat={{ category }}{% endif %}">{{ category }}<span>{{ category.course_set.count }}</span></a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-25 mb-5">
                    <div class="heading">Recent Courses</div>
                    <ul>
                        {% for object in recent_courses %}
                        <li>
                            <a href="{% url 'course:detail' object.id %}" class="d-flex">
                                <figure class="image mr-3">
                                    <img src="{{ object.image.url }}" alt="" class="img-fluid">
                                </figure>
                                <div class="text">
                                    <h3 class="heading">{{ object.title }}</h3>
                                        {% if object.discount_price %}
                                            <del class="mr-3">${{ object.discount_price }}</del>
                                        {% endif %}
                                        {% if object.is_free %}
                                        <span>Free</span>
                                        {% else %}
                                        <span>${{ object.price }}</span>
                                        {% endif %}
                                </div>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="block-26">
                    <h3 class="heading">Tags</h3>
                    <ul>
                        {% for tag in tags %}
                        <li><a href="{% if request.GET %}{{ request.get_full_path }}&tag={{ tag }}{% else %}?tag={{ tag }}{% endif %}">{{ tag }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="py-5 block-22">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-4 mb-md-0 pr-md-5">
                <h2 class="heading">Create cool websites</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
            </div>
            <div class="col-md-6">
                <form method="post" class="subscribe">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.email }}
                        <input type="submit" class="btn btn-primary submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}