apps/main/urls.py
from django.urls import path, include

app_name = 'main'

urlpatterns = [
    path('v1/', include('apps.main.v1.urls'))
]

apps/main/v1/urls.py
from django.urls import path
from .views import index, contact, about

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),

    # local apps
    path('account/', include('apps.account.urls', namespace='account')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('', include('apps.main.urls', namespace='main')),
    path('', RedirectView.as_view(pattern_name='main:index')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/main/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=225)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=225)

    def __str__(self):
        return self.title


class FAQ(models.Model):
    question = models.CharField(max_length=225)

    def __str__(self):
        return self.question


class Answer(models.Model):
    question = models.ForeignKey(FAQ, on_delete=models.CASCADE)
    answer = models.TextField()

    def __str__(self):
        return f'answer for {self.question}'


class Subscribe(models.Model):
    email = models.EmailField(unique=True, db_index=True)

    def __str__(self):
        return self.email


class Contact(models.Model):
    name = models.CharField(max_length=225)
    email = models.EmailField(max_length=225)
    body = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

apps/main/v1/forms.py
from django import forms
from apps.main.models import Subscribe, Contact


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = ['email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({
            'class': 'form-control email',
            'placeholder': 'Enter email',
            'autocomplete': 'off'
        })


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'body']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({
            'type': 'text',
            'id': 'name',
            'class': 'form-control py-2'
        })
        self.fields['email'].widget.attrs.update({
            'type': 'email',
            'id': 'email',
            'class': 'form-control py-2'
        })
        self.fields['body'].widget.attrs.update({
            'type': 'message',
            'id': 'message',
            'class': 'form-control py-2',
            'cols': '30',
            'rows': '8'
        })

apps/main/v1/views.py
from django.shortcuts import render, redirect
from apps.blog.models import Post
from ..models import FAQ, Category
from .forms import SubscribeForm, ContactForm
from apps.course.models import Course
from ...account.models import Profile


def index(request):
    categories = Category.objects.all()
    randomly_5_courses = Course.objects.order_by('?')[:5]
    teachers = Profile.objects.filter(role=1).order_by('?')[:3]
    last_post = Post.objects.last()
    recent_posts = Post.objects.exclude(id=last_post.id).order_by('-id')[:4]

    form = SubscribeForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('.')
    ctx = {
        'form': form,
        'categories': categories,
        'randomly_5_courses': randomly_5_courses,
        'last_post': last_post,
        'recent_posts': recent_posts,
        'teachers': teachers,
    }
    return render(request, 'main/index.html', ctx)


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('.')

    form1 = SubscribeForm(request.POST or None)
    if form1.is_valid():
        form1.save()
        return redirect('.')
    ctx = {
        'form': form,
        'form1': form1,
    }
    return render(request, 'main/contact.html', ctx)


def about(request):
    faq = FAQ.objects.order_by('-id')

    form = SubscribeForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('.')
    ctx = {
        'faq': faq,
        'form': form,
    }
    return render(request, 'main/about.html', ctx)

templates/main/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({% static 'images/big_image_2.jpg' %});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-7 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">About Us</h1>
                    <p class="bcrumb"><a href="{% url 'main:index' %}">Home</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <span class="current">About Us</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="site-section element-animate">
    <div class="container">
        <div class="row">
            <div class="col-md-6 order-md-2">
                <div class="block-16">
                    <figure>
                        <img src="{% static 'images/img_1.jpg' %}" alt="Image placeholder" class="img-fluid">
                    </figure>
                </div>
            </div>
            <div class="col-md-6 order-md-1">
                <div class="block-15">
                    <div class="heading">
                        <h2>Company History</h2>
                    </div>
                    <div class="text mb-5">
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A quibusdam nisi eos accusantium
                            eligendi velit deleniti nihil ad deserunt rerum incidunt nulla nemo eius molestiae
                            architecto beatae asperiores doloribus animi.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos quaerat aliquid blanditiis eum
                            asperiores obcaecati, id officiis voluptate sint est excepturi quam itaque dicta delectus.
                            Consequuntur, blanditiis maxime? Cupiditate, cum.</p>
                        <p>Porro cupiditate doloremque nihil architecto, id nisi tenetur obcaecati, harum nulla aut
                            ipsam sunt ullam eos, ipsa odit voluptatibus veniam. Amet itaque incidunt cumque tenetur,
                            omnis repellat non dolorem nostrum.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="site-section pt-3 element-animate">
    <div class="container">
        <div class="row justify-content-center mb-5 element-animate">
            <div class="col-md-7 text-center section-heading">
                <h2 class="text-primary heading">School Services</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore
                    sapiente.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-3">
                <div class="media block-6 d-block">
                    <div class="icon mb-3"><span class="flaticon-book"></span></div>
                    <div class="media-body">
                        <h3 class="heading">Knowledge is power</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit mess.</p>
                        <p><a href="#" class="more">Read More <span class="ion-arrow-right-c"></span></a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="media block-6 d-block">
                    <div class="icon mb-3"><span class="flaticon-student"></span></div>
                    <div class="media-body">
                        <h3 class="heading">Senior High School</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit mess.</p>
                        <p><a href="#" class="more">Read More <span class="ion-arrow-right-c"></span></a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="media block-6 d-block">
                    <div class="icon mb-3"><span class="flaticon-diploma"></span></div>
                    <div class="media-body">
                        <h3 class="heading">College of Arts &amp; Sciences</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit mess.</p>
                        <p><a href="#" class="more">Read More <span class="ion-arrow-right-c"></span></a></p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="media block-6 d-block">
                    <div class="icon mb-3"><span class="flaticon-professor"></span></div>
                    <div class="media-body">
                        <h3 class="heading">Unmatched Proffessor</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit mess.</p>
                        <p><a href="#" class="more">Read More <span class="ion-arrow-right-c"></span></a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="container site-section element-animate">
    <div class="row justify-content-center mb-5 element-animate">
        <div class="col-md-7 text-center section-heading">
            <h2 class="text-primary heading">Why Choose Us</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore
                sapiente.</p>
        </div>
    </div>
    <div class="block-3 d-md-flex pt-5">
        <div class="image" style="background-image: url('{% static 'images/img_1.jpg' %}'); "></div>
        <div class="text">
            <h4 class="subheading">Nice text here</h4>
            <h2 class="heading">Excellent Teachers</h2>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life
                One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World
                of Grammar.</p>
        </div>
    </div>
    <div class="block-3 d-md-flex">
        <div class="image order-2" style="background-image: url('{% static 'images/img_2.jpg' %}'); "></div>
        <div class="text order-1">
            <h4 class="subheading">Nice text here</h4>
            <h2 class="heading">Outstanding Facilities</h2>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life
                One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World
                of Grammar.</p>
        </div>
    </div>
    <div class="block-3 d-md-flex">
        <div class="image" style="background-image: url('{% static 'images/img_3.jpg' %}'); "></div>
        <div class="text">
            <h4 class="subheading">Nice text here</h4>
            <h2 class="heading">World Class Education</h2>
            <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life
                One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World
                of Grammar.</p>
        </div>
    </div>
</div>
<div class="site-section element-animate">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-7 text-center section-heading">
                <h2 class="text-primary heading">Frequently Asked Questions</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Suscipit qui neque sint eveniet tempore
                    sapiente.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="accordion block-8" id="accordion">
                    {% for object in faq %}
                    <div class="accordion-item">
                        <h3 class="mb-0 heading">
                            <a class="btn-block" data-toggle="collapse" href="#collapseOne" role="button"
                               aria-expanded="true" aria-controls="collapseOne">{{ object.question }}<span
                                    class="icon"></span></a>
                        </h3>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne"
                             data-parent="#accordion">
                            {% for answer in object.answer_set.all %}
                            <div class="body-text">
                                {{ answer.id }} Answer:
                                <p>{{ answer.answer }}</p>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="py-5 block-22">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-4 mb-md-0 pr-md-5">
                <h2 class="heading">Create cool websites</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
            </div>
            <div class="col-md-6">
                <form method="post" class="subscribe">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.email }}
                        <input type="submit" class="btn btn-primary submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/main/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section class="site-hero site-sm-hero overlay" data-stellar-background-ratio="0.5"
         style="background-image: url({% static 'images/big_image_2.jpg' %});">
    <div class="container">
        <div class="row align-items-center justify-content-center site-hero-sm-inner">
            <div class="col-md-7 text-center">
                <div class="mb-5 element-animate">
                    <h1 class="mb-2">Contact Us</h1>
                    <p class="bcrumb"><a href="{% url 'main:index' %}">Home</a> <span
                            class="sep ion-android-arrow-dropright px-2"></span> <span class="current">Contact Us</span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="site-section element-animate">
    <div class="container">
        <div class="row">
            <div class="col-md-8 pr-md-5">
                <form action="#" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="name">Name</label>
                            {{ form.name }}
                        </div>
                        <div class="col-md-6 form-group">
                            <label for="email">Email</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label for="message">Write Message</label>
                            {{ form.body }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <input type="submit" value="Send Message" class="btn btn-primary">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-4">
                <div class="block-23">
                    <h3 class="heading mb-5">Contact Information</h3>
                    <ul>
                        <li><span class="icon ion-android-pin"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                        </li>
                        <li><a href="#"><span class="icon ion-ios-telephone"></span><span
                                class="text">+2 392 3929 210</span></a></li>
                        <li><a href="#"><span class="icon ion-android-mail"></span><span class="text"><span
                                class="__cf_email__" data-cfemail="fc95929a93bc8593898e9893919d9592d29f9391">[email&#160;protected]</span></span></a>
                        </li>
                        <li><span class="icon ion-android-time"></span><span class="text">Monday &mdash; Friday 8:00am - 5:00pm</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<div id="map"></div>
<div class="py-5 block-22">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-6 mb-4 mb-md-0 pr-md-5">
                <h2 class="heading">Create cool websites</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nisi accusantium optio und.</p>
            </div>
            <div class="col-md-6">
                <form method="post" class="subscribe">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form1.email }}
                        <input type="submit" class="btn btn-primary submit" value="Subscribe">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}