apps/account/v1/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView,\
    PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from .views import RegisterView, logout_view, profile_info, profile_update, my_courses


urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', logout_view, name='logout'),

    path('profile_info/', profile_info, name='profile_info'),
    path('profile_update/<int:pk>', profile_update, name='profile_update'),
    path('my_courses/', my_courses, name='my_courses'),

    # change password
    path('password_change/',
         PasswordChangeView.as_view(template_name='account/change_password/password_change_form.html', success_url=reverse_lazy('account:password_change_done')),
         name='password_change'),
    path('password_change/done/',
         PasswordChangeDoneView.as_view(template_name='account/change_password/password_change_done.html'),
         name='password_change_done'),

    # reset password
    path('password_reset/send/',
         PasswordResetView.as_view(template_name='account/reset_password/password_reset_form.html',
                                   email_template_name='account/reset_password/password_reset_email.html',
                                   success_url=reverse_lazy('account:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/',
         PasswordResetDoneView.as_view(template_name='account/reset_password/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/confirm/<str:uidb64>/<str:token>/',
         PasswordResetConfirmView.as_view(template_name='account/reset_password/password_reset_confirm.html',
                                          success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('password_reset/complete/',
         PasswordResetCompleteView.as_view(template_name='account/reset_password/password_reset_complete.html'),
         name='password_reset_complete'),

]

apps/blog/urls.py
from django.urls import path, include

app_name = 'blog'

urlpatterns = [
    path('v1/', include('apps.blog.v1.urls'))
]

apps/course/v1/urls.py
from django.urls import path
# from .views import course_view, course_detail
from .views import CourseListView, CourseDetailView, lesson_detail

urlpatterns = [
    # path('', course_view, name='course_list'),
    # path('detail/<int:pk>/', course_detail, name='detail'),

    path('', CourseListView.as_view(), name = 'course_list'),
    path('detail/<int:pk>/', CourseDetailView.as_view(), name = 'detail'),
    path('detail/<int:course_id>/lesson/<int:pk>/', lesson_detail, name = 'course_lesson_detail'),
]

apps/main/v1/urls.py
from django.urls import path
from .views import index, contact, about

urlpatterns = [
    path('', index, name='index'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),

    # local apps
    path('account/', include('apps.account.urls', namespace='account')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('course/', include('apps.course.urls', namespace='course')),
    path('', include('apps.main.urls', namespace='main')),
    path('', RedirectView.as_view(pattern_name='main:index')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/university/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 23 Feb 2023 14:32:53 GMT -->
<head>
    <title>Free Education Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script nonce="b08cb112-6705-4412-80d1-d4fc24ac520f">
        (function(w,d){!function(f,g,h,i){f[h]=f[h]||{};f[h].executed=[];f.zaraz={deferred:[],listeners:[]};f.zaraz.q=[];f.zaraz._f=function(j){return function(){var k=Array.prototype.slice.call(arguments);f.zaraz.q.push({m:j,a:k})}};for(const l of["track","set","debug"])f.zaraz[l]=f.zaraz._f(l);f.zaraz.init=()=>{var m=g.getElementsByTagName(i)[0],n=g.createElement(i),o=g.getElementsByTagName("title")[0];o&&(f[h].t=g.getElementsByTagName("title")[0].text);f[h].x=Math.random();f[h].w=f.screen.width;f[h].h=f.screen.height;f[h].j=f.innerHeight;f[h].e=f.innerWidth;f[h].l=f.location.href;f[h].r=g.referrer;f[h].k=f.screen.colorDepth;f[h].n=g.characterSet;f[h].o=(new Date).getTimezoneOffset();if(f.dataLayer)for(const s of Object.entries(Object.entries(dataLayer).reduce(((t,u)=>({...t[1],...u[1]})))))zaraz.set(s[0],s[1],{scope:"page"});f[h].q=[];for(;f.zaraz.q.length;){const v=f.zaraz.q.shift();f[h].q.push(v)}n.defer=!0;for(const w of[localStorage,sessionStorage])Object.keys(w||{}).filter((y=>y.startsWith("_zaraz_"))).forEach((x=>{try{f[h]["z_"+x.slice(7)]=JSON.parse(w.getItem(x))}catch{f[h]["z_"+x.slice(7)]=w.getItem(x)}}));n.referrerPolicy="origin";n.src="https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(f[h])));m.parentNode.insertBefore(n,m)};["complete","interactive"].includes(g.readyState)?zaraz.init():f.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document);
    </script>
</head>
<body>

{% include 'navbar.html' %}

{% block content %}



{% endblock %}


{% include 'footer.html' %}


<div id="loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#f4b214"/>
    </svg>
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.0.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');

</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993"
        integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA=="
        data-cf-beacon='{"rayId":"79e0a9e42b3cd947","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2023.2.0","si":100}'
        crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/university/ by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 23 Feb 2023 14:34:01 GMT -->
</html>

templates/footer.html
<footer class="site-footer">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3>University</h3>
                <p>Perferendis eum illum voluptatibus dolore tempora consequatur minus asperiores temporibus.</p>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3 class="heading">Quick Link</h3>
                <div class="row">
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Courses</a></li>
                            <li><a href="#">Pages</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul class="list-unstyled">
                            <li><a href="#">News</a></li>
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Privacy</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3 class="heading">Blog</h3>
                <div class="block-21 d-flex mb-4">
                    <div class="text">
                        <h3 class="heading mb-0"><a href="#">Consectetur Adipisicing Elit</a></h3>
                        <div class="meta">
                            <div><a href="#"><span class="ion-android-calendar"></span> May 29, 2018</a></div>
                            <div><a href="#"><span class="ion-android-person"></span> Admin</a></div>
                            <div><a href="#"><span class="ion-chatbubble"></span> 19</a></div>
                        </div>
                    </div>
                </div>
                <div class="block-21 d-flex mb-4">
                    <div class="text">
                        <h3 class="heading mb-0"><a href="#">Dolore Tempora Consequatur</a></h3>
                        <div class="meta">
                            <div><a href="#"><span class="ion-android-calendar"></span> May 29, 2018</a></div>
                            <div><a href="#"><span class="ion-android-person"></span> Admin</a></div>
                            <div><a href="#"><span class="ion-chatbubble"></span> 19</a></div>
                        </div>
                    </div>
                </div>
                <div class="block-21 d-flex mb-4">
                    <div class="text">
                        <h3 class="heading mb-0"><a href="#">Perferendis eum illum</a></h3>
                        <div class="meta">
                            <div><a href="#"><span class="ion-android-calendar"></span> May 29, 2018</a></div>
                            <div><a href="#"><span class="ion-android-person"></span> Admin</a></div>
                            <div><a href="#"><span class="ion-chatbubble"></span> 19</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3 mb-5 mb-lg-0">
                <h3 class="heading">Contact Information</h3>
                <div class="block-23">
                    <ul>
                        <li><span class="icon ion-android-pin"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                        </li>
                        <li><a href="#"><span class="icon ion-ios-telephone"></span><span
                                class="text">+2 392 3929 210</span></a></li>
                        <li><a href="#"><span class="icon ion-android-mail"></span><span class="text"><span
                                class="__cf_email__" data-cfemail="adc4c3cbc2edd4c2d8dfc9c2c0ccc4c383cec2c0">[email&#160;protected]</span></span></a>
                        </li>
                        <li><span class="icon ion-android-time"></span><span class="text">Monday &mdash; Friday 8:00am - 5:00pm</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row pt-5">
            <div class="col-md-12 text-center copyright">
                <p class="float-md-left">
                    Copyright &copy;<script data-cfasync="false"
                                            src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by
                    <a href="https://colorlib.com/" target="_blank" class="text-primary">Colorlib</a>
                </p>
                <p class="float-md-right">
                    <a href="#" class="fa fa-facebook p-2"></a>
                    <a href="#" class="fa fa-twitter p-2"></a>
                    <a href="#" class="fa fa-linkedin p-2"></a>
                    <a href="#" class="fa fa-instagram p-2"></a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/navbar.html
<header role="banner">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand absolute" href="index-2.html">University</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05"
                    aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse navbar-light" id="navbarsExample05">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'main:index' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="{% url 'course:course_list' %}">Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contact' %}">Contact</a>
                    </li>
                </ul>
                <ul class="navbar-nav absolute-right">
                    <li>
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'account:profile_info' %}">{{ request.user.username }}</a> / <a href="{% url 'account:logout' %}">Logout</a>
                        {% else %}
                            <a href="{% url 'account:login' %}">Login</a> /
                            <a href="{% url 'account:register' %}">Register</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>